<?php

namespace Database\Seeders;

use App\Models\cctvDevices;
use Illuminate\Database\Seeder;

class CctvDeviceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // CCTV devices data based on Barangay 176-E locations
        $cctvDevices = [
            [
                'location_name' => 'Atlantica Langit Road #37',
                'package' => 'Pkg. 4A Atlantika',
                'latitude' => '14.779891404616476',
                'longitude' => '121.0382300966786',
                'primary_rtsp_url' => 'rtsp://192.168.1.101:554/stream1',
                'backup_rtsp_url' => 'rtsp://192.168.1.101:554/stream2',
                'status' => 'active',
                'installation_date' => '2024-01-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Pkg 8 J&T Langit Road #60',
                'package' => 'Pkg. 8A North Cal',
                'latitude' => '14.779392577235317',
                'longitude' => '121.03925075575941',
                'primary_rtsp_url' => 'rtsp://192.168.1.102:554/stream1',
                'backup_rtsp_url' => null,
                'status' => 'active',
                'installation_date' => '2024-02-20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Lacson #36',
                'package' => 'Pkg. 3 Maharlika',
                'latitude' => '14.7647',
                'longitude' => '121.0533',
                'primary_rtsp_url' => 'rtsp://192.168.1.103:554/stream1',
                'backup_rtsp_url' => 'rtsp://192.168.1.103:554/stream2',
                'status' => 'active',
                'installation_date' => '2024-03-10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Gym Langit Road #35',
                'package' => 'Pkg. 4A Atlantika',
                'latitude' => '14.7647',
                'longitude' => '121.0533',
                'primary_rtsp_url' => 'rtsp://192.168.1.104:554/stream1',
                'backup_rtsp_url' => 'rtsp://192.168.1.104:554/stream2',
                'status' => 'maintenance',
                'installation_date' => '2024-01-25',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Atlantica Aklan Wire # 38',
                'package' => 'Pkg. 4B Aklan Wire',
                'latitude' => '14.780688552066275',
                'longitude' => '121.03921875017174',
                'primary_rtsp_url' => 'rtsp://192.168.1.105:554/stream1',
                'backup_rtsp_url' => null,
                'status' => 'active',
                'installation_date' => '2023-12-05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Treasurer Nest #40',
                'package' => 'Pkg. 3 Damayan',
                'latitude' => '14.7647',
                'longitude' => '121.0533',
                'primary_rtsp_url' => 'rtsp://192.168.1.106:554/stream1',
                'backup_rtsp_url' => 'rtsp://192.168.1.106:554/stream2',
                'status' => 'active',
                'installation_date' => '2024-04-18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Pkg 1 Kadiwa Market #75',
                'package' => 'Pkg. 1A Bicolandia',
                'latitude' => '14.7647',
                'longitude' => '121.0533',
                'primary_rtsp_url' => 'rtsp://192.168.1.107:554/stream1',
                'backup_rtsp_url' => null,
                'status' => 'active',
                'installation_date' => '2024-05-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Pkg 5 Buko King #18',
                'package' => 'Pkg. 5 San Roque',
                'latitude' => '14.7647',
                'longitude' => '121.0533',
                'primary_rtsp_url' => 'rtsp://192.168.1.108:554/stream1',
                'backup_rtsp_url' => 'rtsp://192.168.1.108:554/stream2',
                'status' => 'active',
                'installation_date' => '2024-05-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Damayan Crossing #41',
                'package' => 'Pkg. 3 Damayan',
                'latitude' => '14.782812248539633',
                'longitude' => '121.03961195187198',
                'primary_rtsp_url' => 'rtsp://192.168.1.109:554/stream1',
                'backup_rtsp_url' => null,
                'status' => 'active',
                'installation_date' => '2024-06-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Senior High School Back Area',
                'package' => 'Pkg. 7C GS Senior High',
                'latitude' => '14.7647',
                'longitude' => '121.0533',
                'primary_rtsp_url' => 'rtsp://192.168.1.110:554/stream1',
                'backup_rtsp_url' => 'rtsp://192.168.1.110:554/stream2',
                'status' => 'inactive',
                'installation_date' => '2024-06-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Health Center Philrads pkg 7B #2',
                'package' => 'Pkg. 7B PhilRad',
                'latitude' => '14.777615573362453',
                'longitude' => '121.03631418402236',
                'primary_rtsp_url' => 'rtsp://192.168.1.111:554/stream1',
                'backup_rtsp_url' => null,
                'status' => 'active',
                'installation_date' => '2024-07-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Arko ph 9 exit #20',
                'package' => 'Pkg. 9 Plaza Maria Upper',
                'latitude' => '14.7647',
                'longitude' => '121.0533',
                'primary_rtsp_url' => 'rtsp://192.168.1.112:554/stream1',
                'backup_rtsp_url' => 'rtsp://192.168.1.112:554/stream2',
                'status' => 'active',
                'installation_date' => '2024-07-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Pkg 6 & pkg 5 road #32',
                'package' => 'Pkg. 6 Bayanihan',
                'latitude' => '14.7647',
                'longitude' => '121.0533',
                'primary_rtsp_url' => 'rtsp://192.168.1.113:554/stream1',
                'backup_rtsp_url' => null,
                'status' => 'active',
                'installation_date' => '2024-08-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Crasher court pkg 5 #32',
                'package' => 'Pkg. 5 Crasher',
                'latitude' => '14.7647',
                'longitude' => '121.0533',
                'primary_rtsp_url' => 'rtsp://192.168.1.114:554/stream1',
                'backup_rtsp_url' => 'rtsp://192.168.1.114:554/stream2',
                'status' => 'maintenance',
                'installation_date' => '2024-08-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Maharlika 1 Jayoma #52',
                'package' => 'Pkg. 3 Maharlika',
                'latitude' => '14.7647',
                'longitude' => '121.0533',
                'primary_rtsp_url' => 'rtsp://192.168.1.115:554/stream1',
                'backup_rtsp_url' => null,
                'status' => 'active',
                'installation_date' => '2024-09-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Philrads Health Center pkg 7b #1',
                'package' => 'Pkg. 7B PhilRad',
                'latitude' => '14.777615573362453',
                'longitude' => '121.03631418402236',
                'primary_rtsp_url' => 'rtsp://192.168.1.116:554/stream1',
                'backup_rtsp_url' => 'rtsp://192.168.1.116:554/stream2',
                'status' => 'active',
                'installation_date' => '2024-09-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'BFP & Annex pkg 5 #34',
                'package' => 'Pkg. 5 Brgy. Annex (BFP)',
                'latitude' => '14.781270313157409',
                'longitude' => '121.03715807961161',
                'primary_rtsp_url' => 'rtsp://192.168.1.117:554/stream1',
                'backup_rtsp_url' => null,
                'status' => 'active',
                'installation_date' => '2024-10-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Sampalukan Dulo pkg 1 #76',
                'package' => 'Pkg. 1C Sampalukan',
                'latitude' => '14.7647',
                'longitude' => '121.0533',
                'primary_rtsp_url' => 'rtsp://192.168.1.118:554/stream1',
                'backup_rtsp_url' => 'rtsp://192.168.1.118:554/stream2',
                'status' => 'active',
                'installation_date' => '2024-10-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Genesis School pkg 5 #31',
                'package' => 'Pkg. 5 San Roque',
                'latitude' => '14.78125326313561',
                'longitude' => '121.03672820076504',
                'primary_rtsp_url' => 'rtsp://192.168.1.119:554/stream1',
                'backup_rtsp_url' => null,
                'status' => 'active',
                'installation_date' => '2024-11-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Maharlika Dulo Video #51',
                'package' => 'Pkg. 3 Maharlika 2',
                'latitude' => '14.7647',
                'longitude' => '121.0533',
                'primary_rtsp_url' => 'rtsp://192.168.1.120:554/stream1',
                'backup_rtsp_url' => 'rtsp://192.168.1.120:554/stream2',
                'status' => 'active',
                'installation_date' => '2024-11-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert CCTV devices
        cctvDevices::insert($cctvDevices);

        $this->command->info('CCTV devices seeded successfully!');
    }
}
